ipxe: 
    build: .
    command:
        - /builder.sh
        - bin-i386-pcbios/undionly.kpxe
        - bin-i386-efi/ipxe.efi
        - bin-x86_64-efi/ipxe.efi
    volumes:
        - ./builder.sh:/builder.sh:ro
        - ./patches:/patches:ro
        - ./out:/out:rw
    working_dir: /build/ipxe
