ipxe: 
    build: .
    command:
        - /builder.sh
        - bin-i386-pcbios/undionly.kpxe
        - bin-i386-efi/ipxe.efi
        - bin-x86_64-efi/ipxe.efi
        - bin-arm32-efi/snponly.efi
        - bin-arm64-efi/snponly.efi
    volumes:
        - ./builder.sh:/builder.sh:ro
        - ./local-config:/build/ipxe/src/config/homelab:ro
        - ./out:/out:rw
    working_dir: /build/ipxe
